### PR TITLE
feat: add config field to show names. resolves #7

### LINKED ISSUE #7: Feat Request: Set custom names to paths
FIrst of all, amazingly simple plugin. It's **awesome**. 
I see that in the plugin's json. there's a name field for each field. I think It would be neat to be able to show this name in the selection prompt.

After using the plugin a bit more, and reading up on the codebase, I'd be willing to try my hand at implementing this.

### PR DESCRIPTION
**Pull request by vague2k**
## What does this PR do?
- Add a config field called `show_project_names` which is a boolean
- Checks in telescope and vim-ui adapters to check if the `show_project_names` is true

### Telescope implementation
Fairly straight forward
Add a check in `pickers.finder.entry_maker` field in `telescope.lua`  to see if `show_project_names` is true
If it is true, `display = project.name`

### Vim.ui implementation
A bit tricky, i left a `HACK:` comment
We pass an array of project names to show as a list of possible choices. We then loop over all json objects (projects) in the json file and if the choice matches the name property in the object, we use the objects path property as the value to pass to `api.cd_project`

### CODE REVIEW

**Comment by LintaoAmons** [comment]
I don't want that option, if we have the name, we just display both the name and the path~ 
You can have a look, if no other changes, I will merge

**Comment by vague2k** [comment]
I personally thinking an option to show either just the name or just the path, or even both like how you implemented is worth it. But personal opinions aside, looks good to me!

**Comment by LintaoAmons** [comment]
Sound good~

Can you help to add it? I hope to encapsulate this logic in a function, with a signature similar to formEntry(project, max_len) -> string.

**Comment by vague2k** [comment]
Is it fine to add another config field? I can't think of a way to distinguish between explicitly showing either paths or names or both without one

**Comment by LintaoAmons** [comment]
Yeah, I think it's fine to add another optional config field~

**Comment by vague2k** [comment]
Just implemented. Works fine when I tested. let me know if any feedback

**Pull request merged**
