### PR TITLE
add: `tcd` support

### PR DESCRIPTION
**Pull request by mgastonportillo**
This adds support for tcd (`:h tcd`) for those who like working with tabs. Let me know if this is undesired or if I overlooked anything. Thanks!

### CODE REVIEW

**Comment by mgastonportillo** [comment]
I see I broke your styling. Would you mind me adding a stylua config file to prevent this in the future?

**Comment by mgastonportillo** [comment]
Updated readme to match the changes

**Comment by LintaoAmons** [comment]
This looks very useful!

Can you split the format changes and the tcd implementation changes to two commits?

Also the command should follow the *CdProject* prefix pattern

And it would be better if this command will check if there's existing project tab. If yes, just switch to that tab otherwise create a new tab

**Comment by mgastonportillo** [comment]
Awesome! Can definitely do that. Does `:CdTabProject` sound good?

**Comment by mgastonportillo** [comment]
Implemented the check for an existing path in tab as per the requirement. However, I consider it worth mentioning that some users might want to have multiple tabs open with the same directory. Perhaps a config option could be considered in the future to accommodate this behaviour.

I'll wait for a revision of this commit before I continue with the format changes 👍

**Comment by LintaoAmons** [comment]
Hi, I tested it locally.
So it will not create a new tab when trying to `tcd` to a haven't-opened-yet project?

**Comment by LintaoAmons** [comment]
Hi, I tested it locally.
So it will not create a new tab when trying to `tcd` to a haven't-opened-yet project?

**Comment by mgastonportillo** [comment]
Oh, that's interesting. Usually the workflow is you `:tabe` then `:tcd`. This allows you `:tcd` again in the same tab if needed. Although I like this idea of `:CdProjectTab` creating a new tab instead. If you confirm, I will add that feature and force push the same commit 👍

**Comment by LintaoAmons** [comment]
Yes, sounds very good.

sound like a nice workflow, open projects in different tabs and switch between them smoothly

**Comment by mgastonportillo** [comment]
Also added a different message in case current tab is the one holding the targeted path

**Comment by mgastonportillo** [comment]
Now, regarding the format changes, would you like me to just to apply some formatting or also add a stylua file? In case of the latter, does this sound good?
```toml
column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferDouble"
```

**Comment by LintaoAmons** [comment]
Yes, please apply it

**Pull request merged**
